// Probe REAL video metadata (resolution/fps/codec) for the channels that CLAIM
// >=1080p (marker tier q>=4: FHD/RAW/UHD/8K) and cache it, so curation can sort on
// truth instead of the provider's lying "UHD"/"RAW" tags. We skip the ~880 feeds
// whose markers already say <1080p (HD/SD/unmarked) — no point probing those.
//
// Fast + low-overhead: ffprobe reads only stream headers (SPS/VPS) with a tiny
// -probesize and exits (no decode → CPU near-idle); work is network-bound so a
// big concurrency pool is cheap. Re-run periodically (Vercel has no ffprobe).
//
// RESUMABLE + PROGRESSIVE: loads the existing cache and skips anything already
// probed, and flushes the cache to disk atomically every ~2s (and at the end), so
// killing it mid-run never costs more than a couple seconds of work.
//
// REFRESH MODE (`refresh` arg): re-probe ONLY feeds not yet confirmed at their marker
// tier — those missing a reading, or cached BELOW their stated quality (e.g. a "4K" feed
// reading 1080p, probably idle and may return higher). Feeds already at/above their
// marker are left alone — nothing to gain. Retry flaky feeds; OVERWRITE a cached reading
// only when strictly better (height, then fps) — monotonic, so an idle/lower probe never
// downgrades a known peak. A periodic cron (GitHub Actions) thus cheaply chases the gaps.
//
// Usage: bun scripts/probe-quality.ts [concurrency] [refresh]   (creds from env or .env.local)
import { configFromEnv, fetchCuratedChannels } from '../api/_lib.js'
import { rename } from 'node:fs/promises'

const cfg = configFromEnv()
const CONC = Number(Bun.argv[2]) || 64
const REFRESH = Bun.argv.includes('refresh')
const CACHE = 'api/quality-cache.ts'
// The cache is a TS MODULE (not JSON) so the Vercel function can bundle it — native
// ESM there rejects JSON imports without attributes. We write it as `export const`.
const HEAD = '// Auto-generated by scripts/probe-quality.ts — real probed video metadata (resolution/fps).\nexport const QUALITY: Record<string, { w: number; h: number; fps: number; codec: string; name: string } | null> = '

type Meta = { w: number; h: number; fps: number; codec: string; name: string }

// Strictly-better reading (height, then fps) — keeps the cache monotonic in refresh mode.
const better = (a: Meta | null, b: Meta | null | undefined): boolean =>
  !!a && (!b ? true : a.h !== b.h ? a.h > b.h : a.fps > b.fps)

// Resume: pick up whatever a prior (possibly killed) run already saved.
let cache: Record<string, Meta | null> = {}
try { cache = { ...(await import('../api/quality-cache.ts')).QUALITY } } catch { /* fresh run */ }

const channels = await fetchCuratedChannels(cfg)
// A feed "matches its marker" when its real height reaches the tier's nominal resolution.
const nominalH = (q: number) => (q >= 5 ? 2160 : q >= 4 ? 1080 : q >= 3 ? 720 : 0)
const targets = channels.filter((c) => {
  if (c.isEventSlot || c.vodExt || (c.q ?? 0) < 4) return false
  if (!REFRESH) return !(c.streamId in cache)
  // Refresh: skip feeds already confirmed at/above their stated tier; chase only the
  // missing or under-performing ones (a "4K" feed stuck at 1080p is likely just idle).
  const m = cache[c.streamId]
  return !m || m.h < nominalH(c.q ?? 0)
})
const byId = new Map(targets.map((c) => [c.streamId, c.name]))
const ids = [...byId.keys()]

// Progressive save: one debounced writer flushes the whole map atomically
// (temp file + rename, so a crash can't leave a half-written cache).
let dirty = false
let writing = false
async function flush() {
  if (!dirty || writing) return
  writing = true; dirty = false
  await Bun.write(CACHE + '.tmp', HEAD + JSON.stringify(cache) + '\n')
  await rename(CACHE + '.tmp', CACHE)
  writing = false
}
const timer = setInterval(flush, 2000)

async function probe(id: number): Promise<Meta | null> {
  const url = `${cfg.host}/live/${cfg.user}/${cfg.pass}/${id}.ts`
  const p = Bun.spawn(
    ['ffprobe', '-v', 'error', '-user_agent', 'VLC/3.0.18',
     // rw_timeout fails a stalled/dead stream at the network layer fast (the old
     // run's slowness was idle feeds sitting until a long timeout); 2M probesize
     // grabs ~1 keyframe for resolution+fps without streaming the feed.
     '-rw_timeout', '8000000', '-probesize', '2M', '-analyzeduration', '2M',
     '-select_streams', 'v:0',
     '-show_entries', 'stream=width,height,codec_name,r_frame_rate',
     '-of', 'json', url],
    { stdout: 'pipe', stderr: 'ignore', timeout: 10000 },
  )
  const out = await new Response(p.stdout).text()
  await p.exited
  try {
    const v = JSON.parse(out)?.streams?.[0]
    if (v?.width) {
      const [n, d] = String(v.r_frame_rate ?? '').split('/').map(Number)
      return { w: v.width, h: v.height, fps: d ? Math.round((n / d) * 10) / 10 : n, codec: v.codec_name, name: byId.get(id)! }
    }
  } catch { /* unparseable / no video */ }
  return null
}

// Retry flaky feeds (they idle/flicker between events); keep the best reading seen.
async function probeBest(id: number, tries: number): Promise<Meta | null> {
  let best: Meta | null = null
  for (let i = 0; i < tries; i++) {
    const m = await probe(id)
    if (better(m, best)) best = m
    if (best && best.h >= 2160) break
  }
  return best
}

const t0 = Date.now()
let cursor = 0
const worker = async () => {
  while (cursor < ids.length) {
    const id = ids[cursor++]
    const m = await probeBest(id, REFRESH ? 3 : 1)
    // Refresh: only upgrade, never downgrade a known peak. Initial: record result (null = probed).
    if (!REFRESH) { cache[id] = m; dirty = true }
    else if (better(m, cache[id])) { cache[id] = m; dirty = true }
  }
}
await Promise.all(Array.from({ length: Math.min(CONC, ids.length) }, worker))
clearInterval(timer)
dirty = true; await flush()

const ok = ids.filter((id) => cache[id]).length
const total = Object.keys(cache).length
console.log(`${REFRESH ? 'Refreshed' : 'Probed'} ${ids.length} feeds in ${((Date.now() - t0) / 1000).toFixed(1)}s @ conc=${CONC} — ${ok} have signal (cache now ${total})`)
