// Probe REAL video metadata (resolution/fps/codec) for the channels that CLAIM
// >=1080p (marker tier q>=4: FHD/RAW/UHD/8K) and cache it, so curation can sort on
// truth instead of the provider's lying "UHD"/"RAW" tags. We skip the ~880 feeds
// whose markers already say <1080p (HD/SD/unmarked) — no point probing those.
//
// Fast + low-overhead: ffprobe reads only stream headers (SPS/VPS) with a tiny
// -probesize and exits (no decode → CPU near-idle). Concurrency is capped to the
// subscription's currently-free slots; exceeding that limit makes every stream
// return HTTP 458 and can interrupt normal viewing.
//
// RESUMABLE + PROGRESSIVE: loads the existing cache and skips anything already
// probed, and flushes the cache to disk atomically every ~2s (and at the end), so
// killing it mid-run never costs more than a couple seconds of work.
//
// REFRESH MODE (`refresh` arg): re-probe ONLY feeds not yet confirmed at their marker
// tier — those missing a reading, or cached BELOW their stated quality (e.g. a "4K" feed
// reading 1080p, probably idle and may return higher). Feeds already at/above their
// marker are left alone — nothing to gain. Retry flaky feeds; OVERWRITE a cached reading
// only when strictly better (height, then fps) — monotonic, so an idle/lower probe never
// downgrades a known peak. Repeated runs thus chase the gaps and converge on each peak.
//
// TIME BUDGET (`mins=N`, default 30): stop starting new probes once the budget is spent.
// Refresh targets are by definition the feeds that DIDN'T reach their marker — idle or
// dead ones that burn the full ffprobe timeout — and at the one connection this account
// allows, the ~900-feed backlog is several hours of wall clock. Unbounded, that either
// blows GitHub's 6h job limit or holds the only connection slot all day. Bounded, each
// run takes a predictable bite and the monotonic cache keeps the progress.
//
// Usage: bun scripts/probe-quality.ts [concurrency] [refresh] [mins=N]  (creds from env/.env.local)
import { configFromEnv, fetchCuratedChannels, saneFps } from '../api/_lib.js'
import { rename } from 'node:fs/promises'

const cfg = configFromEnv()
const requestedConcurrency = Number(Bun.argv[2]) || 1
const REFRESH = Bun.argv.includes('refresh')
const BUDGET_MIN = Number(Bun.argv.find((a) => a.startsWith('mins='))?.slice(5)) || 30
const CACHE = 'api/quality-cache.ts'
// The cache is a TS MODULE (not JSON) so the Vercel function can bundle it — native
// ESM there rejects JSON imports without attributes. We write it as `export const`.
const HEAD = '// Auto-generated by scripts/probe-quality.ts — real probed video metadata (resolution/fps).\nexport const QUALITY: Record<string, { w: number; h: number; fps: number; codec: string; name: string } | null> = '

type Meta = { w: number; h: number; fps: number; codec: string; name: string }

async function freeConnectionSlots(): Promise<number> {
  const url = new URL('player_api.php', cfg.host + '/')
  url.searchParams.set('username', cfg.user)
  url.searchParams.set('password', cfg.pass)
  const resp = await fetch(url, { headers: { 'User-Agent': 'VLC/3.0.18' } })
  if (!resp.ok) throw new Error(`Account status -> HTTP ${resp.status}`)
  const info = (await resp.json())?.user_info
  const max = Math.max(1, Number(info?.max_connections) || 1)
  const active = Math.max(0, Number(info?.active_cons) || 0)
  if (active >= max) {
    throw new Error(`No free IPTV connection slots (${active}/${max}); stop playback before probing`)
  }
  return max - active
}

const CONC = Math.max(1, Math.min(requestedConcurrency, await freeConnectionSlots()))

// Strictly-better reading (height, then fps) — keeps the cache monotonic in refresh mode.
const better = (a: Meta | null, b: Meta | null | undefined): boolean =>
  !!a && (!b ? true : a.h !== b.h ? a.h > b.h : a.fps > b.fps)

// Resume: pick up whatever a prior (possibly killed) run already saved.
let cache: Record<string, Meta | null> = {}
try { cache = { ...(await import('../api/quality-cache.ts')).QUALITY } } catch { /* fresh run */ }

const channels = await fetchCuratedChannels(cfg)
// A feed "matches its marker" when its real height reaches the tier's nominal resolution.
const nominalH = (q: number) => (q >= 5 ? 2160 : q >= 4 ? 1080 : q >= 3 ? 720 : 0)
const targets = channels.filter((c) => {
  if (c.isEventSlot || c.vodExt || (c.q ?? 0) < 4) return false
  if (!REFRESH) return !(c.streamId in cache)
  // Refresh: skip feeds already confirmed at/above their stated tier; chase only the
  // missing or under-performing ones (a "4K" feed stuck at 1080p is likely just idle).
  const m = cache[c.streamId]
  return !m || m.h < nominalH(c.q ?? 0)
})
const byId = new Map(targets.map((c) => [c.streamId, c.name]))
const ids = [...byId.keys()]

// Progressive save: one debounced writer flushes the whole map atomically
// (temp file + rename, so a crash can't leave a half-written cache).
let dirty = false
let writing = false
async function flush() {
  if (!dirty || writing) return
  writing = true; dirty = false
  await Bun.write(CACHE + '.tmp', HEAD + JSON.stringify(cache) + '\n')
  await rename(CACHE + '.tmp', CACHE)
  writing = false
}
const timer = setInterval(flush, 2000)

async function probe(id: number): Promise<Meta | null> {
  const url = `${cfg.host}/live/${cfg.user}/${cfg.pass}/${id}.ts`
  const p = Bun.spawn(
    ['ffprobe', '-v', 'error', '-user_agent', 'VLC/3.0.18',
     // rw_timeout fails a stalled/dead stream at the network layer fast (the old
     // run's slowness was idle feeds sitting until a long timeout); 2M probesize
     // grabs ~1 keyframe for resolution+fps without streaming the feed.
     '-rw_timeout', '8000000', '-probesize', '2M', '-analyzeduration', '2M',
     '-select_streams', 'v:0',
     '-show_entries', 'stream=width,height,codec_name,r_frame_rate',
     '-of', 'json', url],
    { stdout: 'pipe', stderr: 'ignore', timeout: 10000 },
  )
  const out = await new Response(p.stdout).text()
  await p.exited
  try {
    const v = JSON.parse(out)?.streams?.[0]
    if (v?.width) {
      const [n, d] = String(v.r_frame_rate ?? '').split('/').map(Number)
      // saneFps drops container tick-rate misreads (240/250/300) so `better` can't
      // lock one in as a feed's peak and hide its real rate forever.
      const fps = saneFps(d ? Math.round((n / d) * 10) / 10 : n)
      return { w: v.width, h: v.height, fps, codec: v.codec_name, name: byId.get(id)! }
    }
  } catch { /* unparseable / no video */ }
  return null
}

// Retry flaky feeds (they idle/flicker between events); keep the best reading seen.
async function probeBest(id: number, tries: number): Promise<Meta | null> {
  let best: Meta | null = null
  for (let i = 0; i < tries; i++) {
    const m = await probe(id)
    if (better(m, best)) best = m
    if (best && best.h >= 2160) break
  }
  return best
}

const t0 = Date.now()
const deadline = t0 + BUDGET_MIN * 60_000
let cursor = 0
const worker = async () => {
  while (cursor < ids.length && Date.now() < deadline) {
    const id = ids[cursor++]
    const m = await probeBest(id, REFRESH ? 3 : 1)
    // Refresh: only upgrade, never downgrade a known peak. Initial: record result (null = probed).
    if (!REFRESH) { cache[id] = m; dirty = true }
    else if (better(m, cache[id])) { cache[id] = m; dirty = true }
  }
}
await Promise.all(Array.from({ length: Math.min(CONC, ids.length) }, worker))
clearInterval(timer)
const done = Math.min(cursor, ids.length)
if (done < ids.length) {
  console.log(`Budget of ${BUDGET_MIN}min reached — ${ids.length - done} feeds left for the next run.`)
}
dirty = true; await flush()

// Count over what this run actually ATTEMPTED (`done`), not the whole target list —
// a budgeted run stops early, and reporting the backlog as "probed" overstates it.
const attempted = ids.slice(0, done)
const ok = attempted.filter((id) => cache[id]).length
const total = Object.keys(cache).length
console.log(`${REFRESH ? 'Refreshed' : 'Probed'} ${attempted.length}/${ids.length} feeds in ${((Date.now() - t0) / 1000).toFixed(1)}s @ conc=${CONC} — ${ok} have signal (cache now ${total})`)
